version: '3'
services:
  server:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4001:4001
    volumes:
      - /app/node_modules
      - .:/app/
